List<String> d2chapai = [
  "Dhaka",
  "Biman_Bandar",
  "Joydebpur",
  "Tangail",
  "BBSetu_E",
  "SH M Monsur Ali",
  "Jamtail",
  "Ullapara",
  "Boral_Bridge",
  "Chatmohar",
  "Ishwardi Bypass",
  "Abdulpur",
  "Arani",
  "Rajshahi",
  "Chapai Nawabganj"
];

List<String> d2kox = [
  "Dhaka",
  "Biman_Bandar",
  "Narsingdi",
  "Methikanda",
  "Bhairab_Bazar",
  "Brahmanbaria",
  "Akhaura",
  "Quasba",
  "Shashidal",
  "Cumilla",
  "Laksam",
  "Gunabati",
  "Nangolkot",
  "Hasanpur",
  "Feni",
  "Kumira",
  "Chattogram",
  "Cox's Bazar"
];

List<String> d2n = [
  "Dhaka",
  "Biman_Bandar",
  "Narsingdi",
  "Bhairab_Bazar",
  "Ashuganj",
  "Brahmanbaria",
  "Akhaura",
  "Quasba",
  "Cumilla",
  "Laksam",
  "Natherpetua",
  "Sonaimuri",
  "Bajra",
  "Choumuhani",
  "Maijdi Court",
  "Noakhali"
];

List<String> d2syl = [
  "Dhaka",
  "Biman_Bandar",
  "Narsingdi",
  "Bhairab_Bazar",
  "Ashuganj",
  "Brahmanbaria",
  "Azampur",
  "Mukundapur",
  "Harashpur",
  "Montola",
  "Nayapara",
  "Shahaji_Bazar",
  "Shaistaganj",
  "Sreemangal",
  "Bhanugach",
  "Shamshernagar",
  "Kulaura",
  "Maijgaon",
  "Sylhet",
  "Akhaura",
  "Quasba",
  "Cumilla",
  "Laksam",
  "Natherpetua",
  "Sonaimuri",
  "Bajra",
  "Choumuhani",
  "Maijdi Court",
  "Noakhali"
];

List<String> d2khulna = [
  "Dhaka",
  "Biman_Bandar",
  "Joydebpur",
  "Tangail",
  "BBSetu_E",
  "SH M Monsur Ali",
  "Ullapara",
  "Boral_Bridge",
  "Chatmohar",
  "Ishwardi",
  "Bheramara",
  "Poradaha",
  "Alamdanga",
  "Chuadanga",
  "Kotchandpur",
  "Mubarakganj",
  "Jashore",
  "Noapara",
  "Khulna"
];

List<String> d2panch = [
  "Dhaka",
  "Biman_Bandar",
  "Joydebpur",
  "Tangail",
  "BBSetu_E",
  "Jamtail",
  "Chatmohar",
  "SH M Monsur Ali",
  "Ullapara",
  "Ishwardi Bypass",
  "Natore",
  "Ahsanganj",
  "Santahar",
  "Akkelpur",
  "Joypurhat",
  "Panchbibi",
  "Birampur",
  "Fulbari",
  "Parbatipur",
  "Chirirbandar",
  "Dinajpur",
  "Setabganj",
  "Pirganj",
  "Thakurgaon_Road",
  "Ruhia",
  "Kismat",
  "B Sirajul Islam"
];

List<String> d2saidpur = [
  'Dhaka',
  'Biman_Bandar',
  'Joydebpur',
  "BBSetu_E",
  "Muladhuli",
  'Ishwardi Bypass',
  'Natore',
  "Ahsanganj",
  'Santahar',
  "Akkelpur",
  'Joypurhat',
  'Birampur',
  'Fulbari',
  'Parbatipur',
  'Saidpur',
  'Nilphamari',
  'Domar',
  'Chilahati'
];

List<String> d2rang = [
  'Dhaka',
  'Biman_Bandar',
  'BBSetu_E',
  'Chatmohar',
  'Natore',
  'Santahar',
  'Talora',
  'Bogura',
  'Sonatola',
  'Bonar_Para',
  'Gaibandha',
  'Bamondanga',
  'Pirgacha',
  'Kaunia',
  'Kurigram',
  'Rangpur'
];

List<String> d2lal = [
  'Dhaka',
  'Biman_Bandar',
  'Joydebpur',
  'Tangail',
  'BBSetu_E',
  'SH M Monsur Ali',
  'Ullapara',
  'Boral_Bridge',
  'Azim Nagar',
  'Ishwardi Bypass',
  'Natore',
  'Santahar',
  'Bogura',
  'Sonatola',
  'Bonar_Para',
  'Gaibandha',
  'Bamondanga',
  'Pirgacha',
  'Kaunia',
  'Teesta_Junction',
  'Lalmonirhat',
  'Tushbhandar',
  'Hatibandha',
  'Barkhata',
  'Patgram',
  'Burimari'
];

List<String> d2kishore = [
  "Dhaka",
  "Biman_Bandar",
  "Narsingdi",
  "Methikanda",
  "Bhairab_Bazar",
  "Kuliarchar",
  "Bajitpur",
  "Sararchar",
  "Manikkhali",
  "Gachihata",
  "Kishorganj"
];

List<String> ctg2chand = [
  "Chandpur",
  "Chandpur_Court",
  "Modhu_Road",
  "Hajiganj",
  "Meher",
  "Chitoshi_Road",
  "Laksam",
  "Nangolkot",
  "Hasanpur",
  "Feni",
  "Chattogram"
];

List<String> ctg2syl = [
  "Chattogram",
  "Feni",
  "Nangolkot",
  "Laksam",
  "Cumilla",
  "Quasba",
  "Akhaura",
  "Harashpur",
  "Nayapara",
  "Shaistaganj",
  "Sreemangal",
  "Bhanugach",
  "Shamshernagar",
  "Kulaura",
  "Baramchal",
  "Maijgaon",
  "Sylhet"
];

List<String> raj2said = [
  "Rajshahi",
  "Abdulpur",
  "Natore",
  "Madhnagar",
  "Ahsanganj",
  "Santahar",
  "Akkelpur",
  "Jamalganj",
  "Joypurhat",
  "Panchbibi",
  "Hili",
  "Birampur",
  "Fulbari",
  "Parbatipur",
  "Saidpur",
  "Nilphamari",
  "Domar",
  "Chilahati"
];

List<String> raj2panch = [
  "Rajshahi",
  "Abdulpur",
  "Natore",
  "Madhnagar",
  "Ahsanganj",
  "Santahar",
  "Akkelpur",
  "Joypurhat",
  "Panchbibi",
  "Birampur",
  "Fulbari",
  "Parbatipur",
  "Chirirbandar",
  "Dinajpur",
  "Setabganj",
  "Pirganj",
  "Shibganj",
  "Thakurgaon_Road",
  "Ruhia",
  "Kismat",
  "B Sirajul Islam"
];

List<String> stationsSagardariExpress = [
  "Rajshahi",
  "Abdulpur",
  "Azim Nagar",
  "Ishwardi",
  "Pakshi",
  "Bheramara",
  "Mirpur",
  "Poradaha",
  "Alamdanga",
  "Chuadanga",
  "Darshana_Halt",
  "Safdarpur",
  "Kotchandpur",
  "Mubarakganj",
  "Jashore",
  "Noapara",
  "Khulna"
];

List<String> d2rajpr = [
  "Rajshahi",
  "Ishwardi",
  "Pakshi",
  "Bheramara",
  "Mirpur",
  "Poradaha",
  "Kushtia_Court",
  "Kumarkhali",
  "Khoksha",
  "Pangsha",
  "Kalukhali",
  "Rajbari",
  "Pachuria",
  "Amirabad",
  "Faridpur",
  "Talma",
  "Pukuria",
  "Bhanga",
  "Shibchar",
  "Padma",
  "Mawa",
  "Dhaka"
];

List<String> raj2gopal = [
  "Rajshahi",
  "Ishwardi",
  "Bheramara",
  "Poradaha",
  "Kushtia_Court",
  "Kumarkhali",
  "Khoksha",
  "Pangsha",
  "Kalukhali",
  "Naliagram",
  "Baharpur",
  "Madhukhali",
  "Boalmari_Bazar",
  "Kashiani",
  "Chapta",
  "Choto Bahirbag",
  "Chandradighalia",
  "Gopalganj",
  "Borashi",
  "Gobra"
];

List<String> d2jamal = [
  "Dhaka",
  "Biman_Bandar",
  "Joydebpur",
  "Gafargaon",
  "Mymensingh",
  "Piyarpur",
  "Nandina",
  "Jamalpur_Town",
  "Melandah_Bazar",
  "Islampur_Bazar",
  "Dewanganj_Bazar"
];

List<String> khulna2saidpur = [
  "Khulna",
  "Daulatpur",
  "Noapara",
  "Jashore",
  "Mubarakganj",
  "Kotchandpur",
  "Darshana_Halt",
  "Chuadanga",
  "Alamdanga",
  "Poradaha",
  "Bheramara",
  "Pakshi",
  "Ishwardi",
  "Natore",
  "Ahsanganj",
  "Santahar",
  "Akkelpur",
  "Joypurhat",
  "Birampur",
  "Fulbari",
  "Parbatipur",
  "Saidpur",
  "Nilphamari",
  "Domar",
  "Chilahati"
];

List<String> d2jamaldown = [
  "Dhaka",
  "Biman_Bandar",
  "Joydebpur",
  "Sreepur",
  "Gafargaon",
  "Mymensingh",
  "Piyarpur",
  "Bidyaganj",
  "Narundi",
  "Nandina",
  "Jamalpur_Town",
  "Kendua_Bazar",
  "Jaforshahi",
  "Sarishabari",
  "Tarakandi",
  "Adv. Motiur Rahman",
  "Hemnagar",
  "Bhuapur"
];

List<String> d2siraj = [
  "Dhaka",
  "Biman_Bandar",
  "Joydebpur",
  "Mirzapur",
  "Tangail",
  "BBSetu_E",
  "SH M Monsur Ali",
  "Jamtail",
  "Sirajganjraipur",
  "Sirajganj_Bazar"
];

List<String> d2netro = [
  "Dhaka",
  "Biman_Bandar",
  "Joydebpur",
  "Gafargaon",
  "Mymensingh",
  "Gouripur_Myn",
  "Shyamgonj",
  "Netrakona",
  "Barhatta",
  "Mohanganj"
];

List<String> raj2pabna = [
  "Chapai Nawabganj",
  "Amnura_Bypass",
  "Lolitnagar",
  "Kakonhat",
  "Sitlai",
  "Rajshahi",
  "Sardah_Road",
  "Arani",
  "Abdulpur",
  "Azim Nagar",
  "Ishwardi Bypass",
  "Majhgram",
  "Dashuria",
  "Tebunia",
  "Pabna",
  "Raghabpur",
  "Dublia",
  "Tantibandha",
  "Sathia_Rajapur",
  "Kashinathpur",
  "Badherhat",
  "Dhalarchar"
];

List<String> ctg2jamal = [
  "Chattogram",
  "Bhatiary",
  "Feni",
  "Laksam",
  "Cumilla",
  "Akhaura",
  "Bhairab_Bazar",
  "Sararchar",
  "Kishorganj",
  "Atharabari",
  "Gouripur_Myn",
  "Mymensingh",
  "Piyarpur",
  "Jamalpur_Town"
];

List<String> ctg2cox = [
  "Chattogram",
  "Sholoshohor",
  "Janali_Hat",
  "Patiya",
  "Dohazari",
  "Satkania",
  "Chakaria",
  "Dulahazara",
  "Ramu",
  "Cox's Bazar"
];
