import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:tc/app/routes/app_pages.dart';

class HomeController extends GetxController {
  RxBool isLoading = false.obs;

  final List<String> stationNames = [
    "Abdulpur",
    "Adv. Motiur Rahman",
    "Akhaura",
    "Ahsanganj",
    "Alamdanga",
    "Amirabad",
    "Amnura_Bypass",
    "Arani",
    "Ashuganj",
    "Atharabari",
    "Azampur",
    "Azim Nagar",
    "B Sirajul Islam",
    "Bajitpur",
    "Bajra",
    "Bamondanga",
    "Baramchal",
    "Barhatta",
    "Barkhata",
    "BBSetu_E",
    "Bhairab_Bazar",
    "Bheramara",
    "Bhanga",
    "Bhanugach",
    "Bhatiary",
    "Bhuapur",
    "Bidyaganj",
    "Biman_Bandar",
    "Birampur",
    "Bogura",
    "Bonar_Para",
    "Boral_Bridge",
    "Brahmanbaria",
    "Burimari",
    "Chakaria",
    "Chandpur",
    "Chandpur_Court",
    "Chatmohar",
    "Chilahati",
    "Chirirbandar",
    "Chitoshi_Road",
    "Choumuhani",
    "Chuadanga",
    "Chattogram",
    "Cox's Bazar",
    "Cumilla",
    "Daulatpur",
    "Dashuria",
    "Dewanganj_Bazar",
    "Dhaka",
    "Dhalarchar",
    "Dinajpur",
    "Dohazari",
    "Domar",
    "Dublia",
    "Dulahazara",
    "Faridpur",
    "Feni",
    "Fulbari",
    "Gaibandha",
    "Gafargaon",
    "Gachihata",
    "Gunabati",
    "Gouripur_Myn",
    "Hajiganj",
    "Harashpur",
    "Hatibandha",
    "Hemnagar",
    "Ishwardi",
    "Ishwardi Bypass",
    "Islampur_Bazar",
    "Jaforshahi",
    "Jamalganj",
    "Jamalpur_Town",
    "Jamtail",
    "Janali_Hat",
    "Jashore",
    "Joydebpur",
    "Joypurhat",
    "Kakonhat",
    "Kalukhali",
    "Kaunia",
    "Kendua_Bazar",
    "Khoksha",
    "Kishorganj",
    "Kismat",
    "Kotchandpur",
    "Kulaura",
    "Kuliarchar",
    "Kumarkhali",
    "Kumira",
    "Kurigram",
    "Kushtia_Court",
    "Laksam",
    "Lalmonirhat",
    "Lolitnagar",
    "Maijdi Court",
    "Maijgaon",
    "Manikkhali",
    "Majhgram",
    "Mawa",
    "Meher",
    "Melandah_Bazar",
    "Methikanda",
    "Mirpur",
    "Mirzapur",
    "Modhu_Road",
    "Mohanganj",
    "Montola",
    "Mubarakganj",
    "Mukundapur",
    "Muladhuli",
    "Mymensingh",
    "Nandina",
    "Narundi",
    "Narsingdi",
    "Natherpetua",
    "Natore",
    "Nayapara",
    "Netrakona",
    "Nilphamari",
    "Noapara",
    "Pabna",
    "Padma",
    "Pakshi",
    "Pangsha",
    "Parbatipur",
    "Patiya",
    "Pachuria",
    "Patgram",
    "Panchbibi",
    "Patiya",
    "Piyarpur",
    "Pirganj",
    "Pirgacha",
    "Poradaha",
    "Pukuria",
    "Quasba",
    "Rajbari",
    "Rajshahi",
    "Ramu",
    "Raghabpur",
    "Rangpur",
    "Ruhia",
    "Santahar",
    "Sararchar",
    "Sarishabari",
    "Sardah_Road",
    "Sathia_Rajapur",
    "Saidpur",
    "Sathia_Rajapur",
    "Setabganj",
    "Shaistaganj",
    "Shahaji_Bazar",
    "Shamshernagar",
    "Shashidal",
    "Shibchar",
    "Shibganj",
    "Shyamgonj",
    "Sirajganj_Bazar",
    "Sirajganjraipur",
    "Sitlai",
    "Sonaimuri",
    "Sonatola",
    "Sreepur",
    "Sreemangal",
    "Sylhet",
    "Talma",
    "Talora",
    "Tangail",
    "Tarakandi",
    "Teesta_Junction",
    "Tebunia",
    "Thakurgaon_Road",
    "Tushbhandar",
    "Ullapara",
    "Ramu"
  ];

  RxnString fromStation = RxnString(null);
  RxnString toStation = RxnString(null);
  TextEditingController fromStationText = TextEditingController();
  TextEditingController toStationText = TextEditingController();
  TextEditingController dateText = TextEditingController();

  final List<String> seatClass = [
    'AC_B',
    'AC_S',
    'SNIGDHA',
    'F_BERTH',
    'F_SEAT',
    'F_CHAIR',
    'S_CHAIR',
    'SHOVAN',
    'SHULOV',
    'AC_CHAIR',
  ];

  RxnString selectedClass = RxnString(null);
  TextEditingController seatClasstext = TextEditingController();

  selectDate() {
    showDatePicker(
      context: Get.context!,
      initialDate: DateTime.now(),
      firstDate: DateTime(2020),
      lastDate: DateTime(2030),
    ).then((value) {
      if (value != null) {
        String month = DateFormat.MMM().format(value);
        dateText.text =
            "${value.day.toString().padLeft(2, '0')}-$month-${value.year}";
      }
    });
  }

  void save() {
    Get.toNamed(Routes.TRAIN_DETAILS, arguments: {
      'from': fromStation.value,
      'to': toStation.value,
      'date': dateText.text,
      'class': selectedClass.value,
    });
  }
}
